### PR TITLE
Fixed bad browser position after click on ToC link.

### LINKED ISSUE #61: ToC links scroll down window browser to far.
After main header was transformed to sticky on the top, it's cover ToC link target `<hN>`. We should prevent default link click behaviour, and manually move window to target `<hN>` position with header height subtraction.

### PR DESCRIPTION
**Pull request by postJScriptum**
Fixes #61

### CODE REVIEW

File: assets/scripts/modules/toc.js [hunk 1]
```diff
@@ -18,13 +18,29 @@ export function init() {
 	}
 
 	const tocIcon = toc.querySelector( '.table-of-contents__icon' );
-
+	// toggle ToC visibility
```
Comment (pomek) [inline assets/scripts/modules/toc.js]: A sentence should be beginning with the uppercase letter and ending with a period.
